### ISSUE TITLE
[1.16.5][Forge-36.2.5] Crash on Load, Dedicated Server

### ISSUE THREAD

**Issue by drakray** [Alexthw46/Hexblades#2]
Crash report
https://pastebin.com/Up391ntg

Nothing more to add, worked in single player, crash on load on Ubuntu Dedicated Server

**Comment by Alexthw46** [comment]
I think i found the little error, i just have to move a line of code to be executed only on Client. Will fix on next release, i just have to make sure another thing is working, it won't take much. I'm sorry but i can't easily test what happens in servers so thanks for reporting it.

**Comment by Alexthw46** [comment]
Everything should be fine in the next release, just wait a few days and i'll upload it on curse.

**Comment by drakray** [comment]
While I have you there, do you think it coulld be possible to add Druidcraft SoulFire to the Heat Source like you did the Malum's Ether?

EDIT: When you have the next version published I'll try it again on my server, and going forward, so you'll have a tester for that now lol (if only for the Urn and additional heat source, this mod MUST be in my custom pack XD)

**Comment by Alexthw46** [comment]
Sure it's pretty easy to do (even if it totally conflict if another mod do what i'm doing but there isn't another way right now).

I also found the way to quick test servers, so i can at least prevent dumb errors like this one :P .

That said, i should upload the update smth around tomorrow or the day after. Note : Curse may take care of it but know that it will require GeckoLib and probably Forge updated to 36.2. 
I'll need a short break after that, the new fella took a lot of energy to make and i bet it's still not perfect.
Thanks for support.

**Comment by Alexthw46** [comment]
Uploaded, beta 7b should work as intended.
