### ISSUE TITLE
Flame Prayer reproducable crash

### ISSUE THREAD

**Issue by Rydelfox** [Alexthw46/Hexblades#6]
Each time the flame chant is used on a brazier, Minecraft crashes with Error: java.lang.ClassCastException: elucent.eidolon.tile.BrazierTileEntity cannot be cast to elxthw.hexblades.mixin.BrazierTileEntityMixin Exit code: -1.
I have had other players confirm they also have the issue.
If performed on a server, the server crashes too.
I have confirmed this issue occurs with nothing but Eidolon's Hexblades, Eidolon, GeckoLib, and Curios API (Forge) installed

**Comment by Alexthw46** [comment]
I'm a bit sad that chant was not used (and the bug reported) earlier. I know the solution now, but back mixins and their sneaky problems were still a mystery to me.

The hotfix should come soon.

**Comment by Alexthw46** [comment]
Hope the 0.0.9.3 fix this, i tested it both alone and in a modpack.
